os: linux
language: groovy
jdk: openjdk8
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - GRADLE_VERSION=5.0
  - curl -f -L "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" -o "gradle-${GRADLE_VERSION}-bin.zip"
  - unzip "gradle-${GRADLE_VERSION}-bin.zip"
  - GRADLE_HOME="$(pwd)/gradle-${GRADLE_VERSION}"
  - GRADLE_SCRIPT="${GRADLE_HOME}/bin/gradle"
  - $GRADLE_SCRIPT --version

install:
  - $GRADLE_SCRIPT assemble

script:
  - $GRADLE_SCRIPT check -i

after_success:
  - bash <(curl -s https://codecov.io/bash)

# For deployment to Nexus, configure the `NEXUS_USERNAME` and `NEXUS_PASSWORD` variables:
# - `travis env set NEXUS_USERNAME ...`
# - `travis env set NEXUS_PASSWORD ...`
deploy:
  - provider: script
    skip_cleanup: true
    script: "cp .travis/settings.xml $HOME/.m2/settings.xml && $GRADLE_SCRIPT publish"
    on:
      branch: dev
  - provider: script
    skip_cleanup: true
    script: "cp .travis/settings.xml $HOME/.m2/settings.xml && $GRADLE_SCRIPT publish"
    on:
      branch: release

# For deployment to Docker Hub, configure the `DOCKER_USERNAME` and `DOCKER_PASSWORD` variables:
# - `travis env set DOCKER_USERNAME ...`
# - `travis env set DOCKER_PASSWORD ...` (create a new access token for this purpose)
after_deploy:
  - travis_retry ./.travis/docker_release.sh
  - ./.travis/notify.sh
