version: '3'
services:
  gb-backend-database:
    container_name: gb-backend-database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: gb
      POSTGRES_PASSWORD: gb
      POSTGRES_DB: gb_backend
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
  gb-backend:
    container_name: gb-backend
    image: thehyve/glowing-bear-backend
    ports:
      - 8083:8083
    environment:
      TRANSMART_API_SERVER_URL: ${TRANSMART_API_SERVER_URL}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: transmart-client
      DB_USER: gb
      DB_PASSWORD: gb
      DB_HOST: gb-backend-database
      DB_PORT: 5432
      DB_NAME: gb_backend
    depends_on:
      - gb-backend-database
#      - transmart-api-server
    networks:
      - db-network

volumes:
  db-data:

networks:
  db-network:
    driver: bridge
