version: '3'
services:
  gb-backend-database:
    container_name: gb-backend-database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: gb
      POSTGRES_PASSWORD: gb
      POSTGRES_DB: gb_backend
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gb-backend-db-network

  gb-backend:
    container_name: gb-backend
    image: thehyve/glowing-bear-backend:1.0.6
    ports:
      - 8083:8083
    environment:
      TRANSMART_API_SERVER_URL: ${TRANSMART_API_SERVER_URL}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL:?Please configure KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:?Please configure KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:?Please configure KEYCLOAK_CLIENT_ID}
      DB_USER: gb
      DB_PASSWORD: gb
      DB_HOST: gb-backend-database
      DB_PORT: 5432
      DB_NAME: gb_backend
    volumes:
      - ./extra_certs.pem:/home/gb_backend_usr/extra_certs.pem
    depends_on:
      - gb-backend-database
#      - transmart-api-server
    networks:
      - gb-backend-db-network

volumes:
  db-data:

networks:
  gb-backend-db-network:
    driver: bridge
